name: slicing
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  get: 4.6.5
  getwidget: ^3.0.1
  introduction_screen: ^3.0.2
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
